const DEFAULT_PROJECT_SHEET_TEMPLATE = [
  { id: "s1", is_section_header: true, section: "PRE-CONSTRUCTION", task: "", assigned_to: "", start_date: "", end_date: "", duration: "", status: "", percent_complete: 0, notes: "" },
  { id: "r1", is_section_header: false, section: "", task: "Permits & Approvals", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r2", is_section_header: false, section: "", task: "Site Survey", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r3", is_section_header: false, section: "", task: "Material Procurement", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "s2", is_section_header: true, section: "SITE WORK", task: "", assigned_to: "", start_date: "", end_date: "", duration: "", status: "", percent_complete: 0, notes: "" },
  { id: "r4", is_section_header: false, section: "", task: "Demolition / Clearing", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r5", is_section_header: false, section: "", task: "Excavation", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r6", is_section_header: false, section: "", task: "Grading & Drainage", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "s3", is_section_header: true, section: "FOUNDATION", task: "", assigned_to: "", start_date: "", end_date: "", duration: "", status: "", percent_complete: 0, notes: "" },
  { id: "r7", is_section_header: false, section: "", task: "Footings", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r8", is_section_header: false, section: "", task: "Foundation Walls", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r9", is_section_header: false, section: "", task: "Waterproofing", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "s4", is_section_header: true, section: "FRAMING", task: "", assigned_to: "", start_date: "", end_date: "", duration: "", status: "", percent_complete: 0, notes: "" },
  { id: "r10", is_section_header: false, section: "", task: "Floor Framing", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r11", is_section_header: false, section: "", task: "Wall Framing", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r12", is_section_header: false, section: "", task: "Roof Framing", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "s5", is_section_header: true, section: "MEP ROUGH-IN", task: "", assigned_to: "", start_date: "", end_date: "", duration: "", status: "", percent_complete: 0, notes: "" },
  { id: "r13", is_section_header: false, section: "", task: "Electrical Rough-In", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r14", is_section_header: false, section: "", task: "Plumbing Rough-In", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r15", is_section_header: false, section: "", task: "HVAC Rough-In", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "s6", is_section_header: true, section: "EXTERIOR", task: "", assigned_to: "", start_date: "", end_date: "", duration: "", status: "", percent_complete: 0, notes: "" },
  { id: "r16", is_section_header: false, section: "", task: "Roofing", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r17", is_section_header: false, section: "", task: "Siding / Cladding", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r18", is_section_header: false, section: "", task: "Windows & Doors", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "s7", is_section_header: true, section: "INTERIOR FINISHES", task: "", assigned_to: "", start_date: "", end_date: "", duration: "", status: "", percent_complete: 0, notes: "" },
  { id: "r19", is_section_header: false, section: "", task: "Insulation", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r20", is_section_header: false, section: "", task: "Drywall", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r21", is_section_header: false, section: "", task: "Painting", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r22", is_section_header: false, section: "", task: "Flooring", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r23", is_section_header: false, section: "", task: "Cabinets & Millwork", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "s8", is_section_header: true, section: "MEP TRIM-OUT", task: "", assigned_to: "", start_date: "", end_date: "", duration: "", status: "", percent_complete: 0, notes: "" },
  { id: "r24", is_section_header: false, section: "", task: "Electrical Trim", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r25", is_section_header: false, section: "", task: "Plumbing Fixtures", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r26", is_section_header: false, section: "", task: "HVAC Trim", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "s9", is_section_header: true, section: "CLOSE-OUT", task: "", assigned_to: "", start_date: "", end_date: "", duration: "", status: "", percent_complete: 0, notes: "" },
  { id: "r27", is_section_header: false, section: "", task: "Punch List", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r28", is_section_header: false, section: "", task: "Final Inspection", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r29", is_section_header: false, section: "", task: "Certificate of Occupancy", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
  { id: "r30", is_section_header: false, section: "", task: "Client Walkthrough", assigned_to: "", start_date: "", end_date: "", duration: "", status: "Not Started", percent_complete: 0, notes: "" },
];

export default DEFAULT_PROJECT_SHEET_TEMPLATE;